releases:
  # https://github.com/kubernetes/charts/tree/master/stable/nginx-ingress
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    values:
      - rbac:
          create: true
        controller:
          replicaCount: 2
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
          service:
            type: NodePort
            nodePorts:
              http: 30080
          stats:
            enabled: true
          config:
            # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/configmap.md
            proxy-read-timeout: "180"
            proxy-send-timeout: "180"
            # Large request header (e.g. OIDC proxy)
            proxy-buffer-size: "64k"
            # Large request body (e.g. file upload)
            proxy-body-size: "512m"
            server-tokens: "false"
        defaultBackend:
          replicaCount: 2
          resources:
            limits:
              memory: 16Mi
            requests:
              memory: 16Mi

  # https://github.com/helm/charts/tree/master/stable/efs-provisioner
  - name: efs-provisioner
    namespace: kube-system
    chart: stable/efs-provisioner
    values:
      - efsProvisioner:
          efsFileSystemId: {{ requiredEnv "efs_provisoner_file_system_id" }}
          awsRegion: {{ requiredEnv "AWS_DEFAULT_REGION" }}
          path: /
          storageClass:
            name: efs
            isDefault: true

  # https://github.com/kubernetes/charts/tree/master/stable/kubernetes-dashboard
  - name: kubernetes-dashboard
    namespace: kube-system
    chart: stable/kubernetes-dashboard

  # https://github.com/kubernetes/charts/tree/master/stable/heapster
  - name: heapster
    namespace: kube-system
    chart: stable/heapster
